### ISSUE TITLE
kubernetes: always set resource requests and limits

### ISSUE THREAD

**Issue by laszlocph** [drone/drone-runtime#44]
https://github.com/drone/drone-runtime/pull/29/files implements resource limits perfectly, but it requires users to set the limits per step.

Many of the pipelines don't use this feature, still in Kubernetes it's a best practice to set the resource requests and limits. If not set and the cluster is out of memory then workloads are killed in a random order.

By setting a moderate resource limit will prevent this, and also encourage people to set appropriate limits to their steps.

As a conversation opener the default limit could be 500m CPU and 512M memory

**Comment by philstevenson** [comment]
This all seems pointless if the drone step pods are only allowed to be placed on the node that drone job pod was placed. This means the Job pod get placed with no resource limits or requests and then the step pods which have resource requests and limits, from either drone yaml or a default setting, get forced onto the same node as the job pod. However if there is not enough resources on that node for the step pods they never get scheduled and the cluster won't autoscale because adding nodes won't allow the step pod to be scheduled.

Wouldn't it make more sense to have a pipeline resource setting for all pods related? then at least they could all be pending until the cluster scales then all get placed on the same node.

**Comment by bradrydzewski** [comment]
Please note the experimental kubernetes runtime was deprecated back in April.  It was removed from the documentation, although I think the community-driven helm chart still defaults to this deprecated runtime. See this thread https://github.com/drone/drone-runtime/issues/69 for more details on why it was deprecated and future plans for kubernetes.
